//bottom level
//(1,4,1)>15 (2,4,1)>11 (3,4,1)>7 (4,4,1)>3
//(1,3,1)>14 (2,3,1)>10 (3,3,1)>6 (4,3,1)>2
//(1,2,1)>13 (2,2,1)>9 (3,2,1)>5 (4,2,1)>1
//(1,1,1)>12 (2,1,1)>8 (3,1,1)>4 (4,1,1)>0

int del=100;    //set delay time
void reset();    //reset all pins
void in_order();    //let LED lighten in order
void same_color();    //let the same color LED lighten together
void setup()
{
    int i;
    for(i=0;i<20;i++)
        pinMode(i,OUTPUT);
}
void loop() 
{
    in_order();
    same_color();
    for(int i=0;i<16;i++)
    digitalWrite(i,HIGH);
    for(int i=16;i<20;i++)
    digitalWrite(i,LOW);
    delay(1000000);
}

void reset()
{
    int a,b;
    for(a=0;a<16;a++)
        digitalWrite(a,LOW);  
    for(b=16;b<20;b++)
        digitalWrite(b,HIGH);
}

void in_order()
{
    int x,y,z;
    reset();
    for(y=16;y<20;y++)
    {
        for(z=12;z<16;z++)
        {
            for(x=0;x<4;x++)
            {
                digitalWrite(z-4*x,HIGH);
                digitalWrite(y,LOW);
                delay(del);
                reset();
            }
        }
    }
    for(z=12;z<16;z++)
    {
        for(y=16;y<20;y++)
        {
            for(x=0;x<4;x++)
            {
                digitalWrite(z-4*x,HIGH);
                digitalWrite(y,LOW);
                delay(del);
                reset();
            }
        }
    }
}

void same_color()
{
    int i;   //counter
    int f=1;    //to control the frequency
    int del=240;   //2,3,4的倍數
    reset();
    
    digitalWrite(12,HIGH);
    digitalWrite(16,LOW);
    delay(del/f);
    reset();
    f++;
    
    for(i=0;i<del/2/f;i++)
    {
        digitalWrite(8,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(13,HIGH);
        digitalWrite(16,LOW);
        delay(1);
        reset();
        digitalWrite(12,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
    }
    f++;

    for(i=0;i<del/3/f;i++)
    {
        digitalWrite(4,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(9,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(14,HIGH);
        digitalWrite(16,LOW);
        delay(1);
        reset();
        digitalWrite(8,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(13,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
        digitalWrite(12,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
    }
    f++;

    for(i=0;i<del/4/f;i++)
    {
        digitalWrite(0,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(5,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(10,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(15,HIGH);
        digitalWrite(16,LOW);
        delay(1);
        reset();
        digitalWrite(4,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(9,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(14,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
        digitalWrite(8,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(13,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
        digitalWrite(12,HIGH);
        digitalWrite(19,LOW);
        delay(1);
        reset();
    }
    f++;

    for(i=0;i<del/4/f;i++)
    {
        digitalWrite(1,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(6,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(11,HIGH);
        digitalWrite(16,LOW);
        delay(1);
        reset();
        digitalWrite(0,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(5,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(10,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(15,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
        digitalWrite(4,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(9,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(14,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
        digitalWrite(13,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(8,HIGH);
        digitalWrite(19,LOW);
        delay(1);
        reset();
    }
    f++;

    for(i=0;i<del/4/f;i++)
    {
        digitalWrite(2,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(7,HIGH);
        digitalWrite(16,LOW);
        delay(1);
        reset();
        digitalWrite(1,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(6,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(11,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
        digitalWrite(0,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(5,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(10,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(15,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
        digitalWrite(14,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(9,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(4,HIGH);
        digitalWrite(19,LOW);
        delay(1);
        reset();
    }
    f--;

    for(i=0;i<del/3/f;i++)
    {
        digitalWrite(3,HIGH);
        digitalWrite(16,LOW);
        delay(1);
        reset();
        digitalWrite(2,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(7,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
        digitalWrite(1,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(6,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(11,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
        digitalWrite(15,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(10,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(5,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(0,HIGH);
        digitalWrite(19,LOW);
        delay(1);
        reset();
    }
    f--;

    for(i=0;i<del/3/f;i++)
    {
        digitalWrite(3,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
        digitalWrite(2,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(7,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
        digitalWrite(1,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(6,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(11,HIGH);
        digitalWrite(19,LOW);
        delay(1);
        reset();
    }
    f--;

    for(i=0;i<del/2/f;i++)
    {
        digitalWrite(3,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
        digitalWrite(2,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(7,HIGH);
        digitalWrite(19,LOW);
        delay(1);
        reset();
    }
    f--;

    digitalWrite(3,HIGH);
    digitalWrite(19,LOW);
    delay(del/f);
    reset();
    f++;

    for(i=0;i<del/2/f;i++)
    {
        digitalWrite(3,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
        digitalWrite(2,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(7,HIGH);
        digitalWrite(19,LOW);
        delay(1);
        reset();
    }
    f++;

    for(i=0;i<del/3/f;i++)
    {
        digitalWrite(3,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
        digitalWrite(2,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(7,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
        digitalWrite(1,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(6,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(11,HIGH);
        digitalWrite(19,LOW);
        delay(1);
        reset();
    }
    f++;

    for(i=0;i<del/3/f;i++)
    {
        digitalWrite(3,HIGH);
        digitalWrite(16,LOW);
        delay(1);
        reset();
        digitalWrite(2,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(7,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
        digitalWrite(1,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(6,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(11,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
        digitalWrite(15,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(10,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(5,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(0,HIGH);
        digitalWrite(19,LOW);
        delay(1);
        reset();
    }
    f++;

    for(i=0;i<del/4/f;i++)
    {
        digitalWrite(2,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(7,HIGH);
        digitalWrite(16,LOW);
        delay(1);
        reset();
        digitalWrite(1,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(6,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(11,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
        digitalWrite(0,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(5,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(10,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(15,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
        digitalWrite(14,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(9,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(4,HIGH);
        digitalWrite(19,LOW);
        delay(1);
        reset();
    }
    f--;

    for(i=0;i<del/4/f;i++)
    {
        digitalWrite(1,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(6,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(11,HIGH);
        digitalWrite(16,LOW);
        delay(1);
        reset();
        digitalWrite(0,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(5,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(10,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(15,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
        digitalWrite(4,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(9,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(14,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
        digitalWrite(13,HIGH);
        digitalWrite(19,LOW);
        digitalWrite(8,HIGH);
        digitalWrite(19,LOW);
        delay(1);
        reset();
    }
    f--;

    for(i=0;i<del/4/f;i++)
    {
        digitalWrite(0,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(5,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(10,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(15,HIGH);
        digitalWrite(16,LOW);
        delay(1);
        reset();
        digitalWrite(4,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(9,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(14,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
        digitalWrite(8,HIGH);
        digitalWrite(18,LOW);
        digitalWrite(13,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
        digitalWrite(12,HIGH);
        digitalWrite(19,LOW);
        delay(1);
        reset();
    }
    f--;

    for(i=0;i<del/3/f;i++)
    {
        digitalWrite(4,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(9,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(14,HIGH);
        digitalWrite(16,LOW);
        delay(1);
        reset();
        digitalWrite(8,HIGH);
        digitalWrite(17,LOW);
        digitalWrite(13,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
        digitalWrite(12,HIGH);
        digitalWrite(18,LOW);
        delay(1);
        reset();
    }
    f--;

    for(i=0;i<del/2/f;i++)
    {
        digitalWrite(8,HIGH);
        digitalWrite(16,LOW);
        digitalWrite(13,HIGH);
        digitalWrite(16,LOW);
        delay(1);
        reset();
        digitalWrite(12,HIGH);
        digitalWrite(17,LOW);
        delay(1);
        reset();
    }
    f--;

    digitalWrite(12,HIGH);
    digitalWrite(16,LOW);
    delay(del);
    reset();
    f--;
}
